<?php

define('SENDSTUDIO_DATABASE_TYPE', 'mysql');
define('SENDSTUDIO_DATABASE_USER', 'redeseit_root');
define('SENDSTUDIO_DATABASE_PASS', '$_M@n4g3m3ntdb531736_$');
define('SENDSTUDIO_DATABASE_HOST', 'localhost');
define('SENDSTUDIO_DATABASE_NAME', 'redeseit_nwletters');
define('SENDSTUDIO_TABLEPREFIX', '');
define('SENDSTUDIO_LICENSEKEY', '');
define('SENDSTUDIO_APPLICATION_URL', 'http://newsletter.redeseitec.com.br');
define('SENDSTUDIO_SMTP_SERVER', '');
define('SENDSTUDIO_SMTP_USERNAME', '');
define('SENDSTUDIO_SMTP_PASSWORD', '');
define('SENDSTUDIO_SMTP_PORT', '');
define('SENDSTUDIO_SERVERTIMEZONE', 'GMT-3:00');
define('SENDSTUDIO_FORCE_UNSUBLINK', '1');
define('SENDSTUDIO_HTMLFOOTER', '');
define('SENDSTUDIO_TEXTFOOTER', '');
define('SENDSTUDIO_MAXHOURLYRATE', '0');
define('SENDSTUDIO_MAXOVERSIZE', '0');
define('SENDSTUDIO_CRON_ENABLED', '');
define('SENDSTUDIO_DEFAULTCHARSET', 'ISO-8859-1');
define('SENDSTUDIO_EMAIL_ADDRESS', 'ramirest@gmail.com');
define('SENDSTUDIO_IPTRACKING', '1');
define('SENDSTUDIO_MAX_IMAGEWIDTH', '700');
define('SENDSTUDIO_MAX_IMAGEHEIGHT', '400');
define('SENDSTUDIO_BOUNCE_ADDRESS', '');
define('SENDSTUDIO_BOUNCE_SERVER', '');
define('SENDSTUDIO_BOUNCE_USERNAME', '');
define('SENDSTUDIO_BOUNCE_PASSWORD', '');
define('SENDSTUDIO_BOUNCE_IMAP', '');
define('SENDSTUDIO_BOUNCE_EXTRASETTINGS', '');
define('SENDSTUDIO_IS_SETUP', 1);

?>
